package com.dp.digip.models;


import javax.persistence.*;
import org.hibernate.search.annotations.*;
import javax.validation.constraints.NotNull;
import java.sql.Blob;
import java.io.Serializable;
import java.util.Date;
import java.util.Set;
/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Indexed
@Table(name = "event")
public class Event implements Serializable{

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    	@Id
    	@GeneratedValue(strategy = GenerationType.AUTO)
    	@Column( unique = true,nullable = false)
    	private Long id;

	@Field
    	@Column( unique = true,nullable = false)
    	private String name;
/*
    	@Column( unique = false,nullable = false)
    	private String country;

    	@Column( unique = false,nullable = false)
    	private String region;

    	@Column( unique = false,nullable = false)
   	private String municipality;

    	@Column( unique = false , nullable = false)
    	private String address;

    	@Column( unique = false,nullable = false)
    	private String address_number;

    	@Column( unique = false, nullable = false)
    	private int supervision;

    	@Column( unique = false,nullable = false)
    	private int people_with_special_needs;

    	@Column( unique = false,nullable = true)
    	private int age_from;

    	@Column( unique = false,nullable = true)
    	private int age_to;
*/
    	@Column( unique = false,nullable = false)
    	private int cost;
/*
    	@Column( unique = false,nullable = false)
    	private String start_time;
*/
    	@Temporal(TemporalType.DATE)
    	@Column( unique = false, nullable = false)
   	private Date date;
/*  
    	@Column( unique = false, nullable = true)
    	private String duration;

    	@Column ( unique = false , nullable = true)
    	private int parking;

    	@Column ( unique = false , nullable = true)
    	private int parent_participation;


    	@Column ( unique =false , nullable = false)
    	private int online;

*/
    	@Column ( unique = false , nullable = false)
    	private int tickets_initial;

    	@Column ( unique = false , nullable = false)
    	private int tickets_remaining;

	@Field
    	@Column( unique = false, nullable = true)
    	private String description;

    	@Lob
    	@Column(length=10000000 , nullable = true)	
    	private byte[] image;

	@ManyToOne
	@JoinColumn(name = "user_id",nullable = false, referencedColumnName="id")
	private User user;

	@OneToMany(mappedBy = "event",cascade = CascadeType.ALL)
	private Set<Transaction> transactions;

	@OneToMany(mappedBy = "event", cascade = CascadeType.ALL)
	private Set<Comment> comments;

	public Event(){}

    	public Event(String name,byte[] image,String description,User user) {
		this.name = name;
		this.image = image;
		this.description = description;
		this.user = user;
	}

    	public Event(long id) {
        	this.id = id;
    	}

    // Getter and setter methods
    //
    	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Transaction> getTransactions(){
		return this.transactions;
	}

	public void setTransactions( Set<Transaction> transaction){
		this.transactions = transaction;
	}

	public Set<Comment> getComments(){
		return this.comments;
	}

	public void setComments( Set<Comment> comments){
		this.comments = comments;
	}
/*	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getMunicipality() {
		return municipality;
	}

	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress_number() {
		return address_number;
	}

	public void setAddress_number(String address_number) {
		this.address_number = address_number;
	}

	public int getSupervision() {
		return supervision;
	}

	public void setSupervision(int supervision) {
		this.supervision = supervision;
	}

	public int getPeople_with_special_needs() {
		return people_with_special_needs;
	}

	public void setPeople_with_special_needs(int people_with_special_needs) {
		this.people_with_special_needs = people_with_special_needs;
	}

	public int getAge_from() {
		return age_from;
	}

	public void setAge_from(int age_from) {
		this.age_from = age_from;
	}

	public int getAge_to() {
		return age_to;
	}

	public void setAge_to(int age_to) {
		this.age_to = age_to;
	}
*/
	public int getCost() {
		return cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}
/*
	public String getStart_time() {
		return this.start_time;
	}
	public void setStart_time(String start_time) {
		this.start_time = start_time;
	}
*/
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
/*
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public int getParking() {
		return parking;
	}

	public void setParking(int parking) {
		this.parking = parking;
	}

	public int getParent_participation() {
		return parent_participation;
	}

	public void setParent_participation(int parent_participation) {
		this.parent_participation = parent_participation;
	}

	public int getOnline() {
		return online;
	}

	public void setOnline(int online) {
		this.online = online;
	}
*/
	public int getTicketsInitial() {
		return tickets_initial;
	}

	public void setTicketsInitial(int ticket_number_initial) {
		this.tickets_initial = ticket_number_initial;
	}

	public int getTicketsRemaining() {
		return tickets_remaining;
	}

	public void setTicketsRemaining(int ticket_number_remaining) {
		this.tickets_remaining = ticket_number_remaining;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getImage() {
		return image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public User getUser(){
		return this.user;
	}

	public void setUser(User user){
		this.user = user;
	}

}
