package com.dp.digip.models;

/**
 * Created by Christos on 24/5/2017.
 */

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.sql.Blob;

@Entity
@Table(name = "parent")
public class Parent {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;


    @NotNull
    private String name;

    @NotNull
    private String surname;

    @NotNull
    private String fathers_name;

    @NotNull
    private String email;

    @NotNull
    private String cellphone;

    @NotNull
    private String phone;

    @NotNull
    private String region;

    @NotNull
    private String municipality;

    @NotNull
    private String country;

    //there are 2 types of Blob
    @NotNull
    private Blob participation_certificate;

    //there are 2 types of Blob
    @NotNull
    private Blob avatar;

    @NotNull
    private Integer money;

    @NotNull
    private String pass;

    public Parent(String email, String name, String surname, String fathers_name, String pass,
                  String cellphone, String phone, String region, String municipality,
                  String country, Blob participation_certificate, Blob avatar, Integer money)
    {
        this.email = email;
        this.name = name;
        this.surname = surname;
        this.fathers_name = fathers_name;
        this.pass = pass;
        this.cellphone = cellphone;
        this.phone = phone;
        this.region = region;
        this.municipality = municipality;
        this.country = country;
        this.participation_certificate = participation_certificate;
        this.avatar = avatar;
        this.money = money;
    }

    //SETTERS

    public void setId(Long id1){
        id = id1;
    }

    public void setEmail(String email1){
        email = email1;
    }

    public void setName(String name1){
        name = name1;
    }

    public void setSurname(String surname1){
        surname = surname1;
    }

    public void setFathers_name(String fathers_name1){
        fathers_name = fathers_name1;
    }

    public void setCellphone(String cellphone1){
        cellphone = cellphone1;
    }

    public void setPhone(String phone1){
        phone = phone1;
    }

    public void setRegion(String region1){
        region = region1;
    }

    public void setMunicipality(String municipality1){
        municipality = municipality1;
    }

    public void setCountry(String country1){
        country = country1;
    }

    public void setParticipation_certificate(Blob part_cert){
        participation_certificate = part_cert;
    }

    public void setAvatar(Blob avatar1){
        avatar = avatar1;
    }

    public void setMoney(Integer money1){
        money = money1;
    }

    public void setPass(String pass1){
        pass = pass1;
    }



    //GETTERS

    public Long getId(){
        return id;
    }

    public String getEmail(){
        return email;
    }

    public String getName( ){
        return name;
    }

    public String etSurname( ){
        return surname;
    }

    public String getFathers_name( ){
       return fathers_name;
    }

    public String getCellphone( ){
        return cellphone;
    }

    public String getPhone( ){
        return phone;
    }

    public String getRegion( ){
        return region;
    }

    public String getMunicipality( ){
        return municipality;
    }

    public String getCountry( ){
        return country;
    }

    public Blob getParticipation_certificate( ){
        return participation_certificate;
    }

    public Blob getAvatar( ){
        return avatar;
    }

    public Integer getMoney( ){
        return money;
    }

    public String getPass( ){
        return pass;
    }
}
