package com.dp.digip.models;

/**
 * Created by Nikos on 21/5/2017.
 */
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "users")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

//    // The user's name
//    @NotNull
//    private String username;
//
//    @NotNull
//    private String pass_hash;
//
//    @NotNull
//    private String salt;
//
//    @NotNull
//    private Integer type_user;

    @NotNull
    private String name;

    @NotNull
    private String email;



//    public User(String username, String pass_hash, String salt, Integer type_user) {
//        this.username = username;
//        this.pass_hash = pass_hash;
//        this.salt = salt;
//        this.type_user = type_user;
//    }

    //GETTERS
//    public long getId() {
//        return id;
//    }
//
//    public String getPass_hash() {
//        return pass_hash;
//    }
//
//    public String getUsername() {
//        return username;
//    }
//
//    public Integer getType_user(){return type_user;}
//
//    public String getSalt(){return salt;}
//
//
//    //SETTERS
//    public void setId(long value) {
//        this.id = value;
//    }
//
//    public void setPass_hash(String pass_hash1) {
//        //TODO: encrypt the passed argument first
//        this.pass_hash = pass_hash1;
//    }
//
//    public void setUsername(String username1) {
//        this.username = username1;
//    }
//
//    public void setType_user(Integer type_user1){
//        this.type_user = type_user1;
//    }
//
//    public void setSalt(String salt1){
//        this.salt = salt1;
//    }
    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String email, String name) {
        this.email = email;
        this.name = name;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }


}